
SETTING_SERVER_CLOCK = "RAZBERRY_CLOCK"
SETTING_SERVER_TIME  = "RAZBERRY_TIME"

SETTING_LAST_UPDATE  = "LAST_UPDATED"

SETTING_SERVER_ADDRRESS = "RAZBERRY_SERVER"
SETTING_SERVICE_TIMEOUT = "SERVICE_TIMEOUT"

CLASS_SWITCH_BINARY = '37'

CLASS_VERSION = '134'